"""Outbound channel port — matches the existing channels/OutboundSender."""

from __future__ import annotations

from typing import Protocol


class OutboundSender(Protocol):
    async def send_message(self, to: str, text: str) -> bool: ...
    async def send_image(self, to: str, image_url: str, caption: str = "") -> bool: ...
    async def send_buttons(
        self, to: str, body_text: str, buttons: list[str]
    ) -> bool: ...
    async def send_read_receipt(self, to: str, message_id: str) -> None: ...
    async def download_media(self, media_id: str) -> bytes | None: ...
    async def send_alert(self, text: str) -> None: ...
    def is_fasilitator(self, sender_id: str) -> bool: ...
